### ISSUE TITLE
Error on the last 2 rows of commands

### ISSUE THREAD

**Issue by bingwei9924** [vappiah/DataMiner#1]
I tried the command line by line and there are 2 error from the last 2 lines, as mentioned below:

My Code:
import os
os.chdir('C:/Users/bingw/Desktop/Oct 2021/DataMiner-main')
from tcga_downloader import *
ids=get_ids('manifest.txt')
payload=prepare_payload(ids,data_type='Gene Expression Quantification')
metadata=get_metadata(payload) 
download_data(metadata,sep= '\t' ,outdir='BRCA') -->> raise the EmptyDataError: No columns to parse from file

Error:
runfile('C:/Users/bingw/Desktop/Oct 2021/Python/Python Learning/Variables/1st try.py', wdir='C:/Users/bingw/Desktop/Oct 2021/Python/Python Learning/Variables')
Reloaded modules: tcga_downloader
curl --request POST --header "Content-Type: application/json" --data @payloadv3.txt 'https://api.gdc.cancer.gov/files' > Metadata.tsv
Traceback (most recent call last):

  File "C:\Users\bingw\Desktop\Oct 2021\Python\Python Learning\Variables\1st try.py", line 7, in <module>
    download_data(metadata,sep= '\t' ,outdir='BRCA')

  File "C:\Users\bingw\Desktop\Oct 2021\DataMiner-main\tcga_downloader.py", line 112, in download_data
    data_df=pd.read_csv(metadatafile,sep=sep)

  File "C:\Users\bingw\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\bingw\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)

  File "C:\Users\bingw\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)

  File "C:\Users\bingw\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]

  File "C:\Users\bingw\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)

  File "pandas\_libs\parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__

EmptyDataError: No columns to parse from file

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 'https

**Comment by vappiah** [comment]
It seems you are parsing an empty file to the download_data function
After issuing the _get_metadata(payload)_ function, check to see if a  file called Metadata.tsv is created in the working directory

**Comment by bingwei9924** [comment]
Yes sir, the Metadata file appears but it has nothing inside.

**Comment by bingwei9924** [comment]
Sorry sir, what should I do in the next step?

**Comment by vappiah** [comment]
Check if your manifest.txt file exists

**Comment by bingwei9924** [comment]
Yes sir, it exists and I put it in the same folder of the downloaded code.

**Comment by vappiah** [comment]
Could you run the commands in a linux environment.? If it works, then it may be a windows problem.
I only tested the scripts in a linux environment.

**Comment by bingwei9924** [comment]
Let me try to install Linux and try later, thanks

**Comment by vappiah** [comment]
You can set up a virtual linux environment using virtualbox (https://www.youtube.com/watch?v=D3S6bIjWbDg&t=17s)

**Comment by bingwei9924** [comment]
Hi Sir, the code can be run smoothly in linux environment, thank you!

**Comment by vappiah** [comment]
Glad it worked.

**Comment by bingwei9924** [comment]
Hi Sir, Sorry but is there any tutorial video in converting the Ensembl IDs to gene symbols?

**Comment by vappiah** [comment]
At the moment I don't have any video on that.

**Comment by bingwei9924** [comment]
Okay, noted with thanks

**Comment by bingwei9924** [comment]
Sorry sir, just to confirm, the final file that we get is Ensembl Ids (with ENSGXXXXXX) and what?

**Comment by vappiah** [comment]
The final file contains the ensembl IDs and the gene counts.

**Comment by bingwei9924** [comment]
Hi sir, sorry to ask again, can I get the genes according to stages of cancer?

**Comment by vappiah** [comment]
Yes. its possible. You have to check for the clinical information
